### ISSUE TITLE
torch.unique problem

### ISSUE THREAD

**Issue by job2003** [ne7ermore/yolo-v3#2]
/usr/local/lib/python3.5/dist-packages/torch/nn/functional.py:1749: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode))
Traceback (most recent call last):
  File "detect.py", line 45, in <module>
    main()
  File "detect.py", line 37, in main
    outputs = ip.predict(model(batch), nms_conf=args.nms_thresh)
  File "/home/user/workspace/yolo-v3-pytorch/img_loader.py", line 107, in predict
    img_classes = torch.unique(image_pred_[:, -1])
  File "/usr/local/lib/python3.5/dist-packages/torch/functional.py", line 359, in unique
    return_inverse=return_inverse,
RuntimeError: unique is currently CPU-only, and lacks CUDA support. Pull requests welcome!

what is the problem?

**Comment by ne7ermore** [comment]
ur Pytorch version? plz

**Comment by job2003** [comment]
torch-0.4.0

**Comment by ne7ermore** [comment]
fixed, plz update torch to 0.4.1 and git pull code again
